### ISSUE TITLE
Could not find a JavaScript runtime. が表示されてモロヘイヤHOMEが利用できない

### ISSUE THREAD

**Issue by karasugawasu** [pooza/mulukhiya-toot-proxy#2076]
## 概要

モロヘイヤHOMEへアクセスすると、`Could not find a JavaScript runtime`と言うエラーが発生し、
モロヘイヤHOMEの機能が利用できない。

**※後述の通りひとまず解決しています**

## 現象

Discordに送られてきたエラーです。(Syslogのは長かったので必要であれば張ります）
```
:class: Ginseng::Error
:message: Could not find a JavaScript runtime. See https://github.com/rails/execjs
  for a list of available runtimes.
:source_class: ExecJS::RuntimeUnavailable
:backtrace:
- "/home/karasugawa/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in
  autodetect'"
- "/home/karasugawa/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/execjs-2.7.0/lib/execjs.rb:5:in
  <module:ExecJS>'"
- "/home/karasugawa/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/execjs-2.7.0/lib/execjs.rb:4:in
  <main>'"
- "/home/karasugawa/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in
  require'"
- "/home/karasugawa/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in
  require'"
- "/home/karasugawa/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in
  block in require_with_bootsnap_lfi'"
```

## 期待される動作

モロヘイヤHOMEが利用できる

## 再現手順

1.モロヘイヤHOMEにアクセス

## 環境

mulukhiya-toot-proxy 4.2.8
Ubuntu 20.10
Pleroma 2.2.50-973-gdb716f86-develop(Docker環境) （2.3に上げたつもりだったのに・・・）

## 試したこと

エラーに記載されている通り、ランタイムが必要とのことでしたのでとりあえずNode.jsを入れたところ、
この問題は解消されました。
（おそらくDocker使っているのでサーバ側にほとんど何も入っていないから？）

すでに解消していますが、対応として正しいかご確認いただけますか。

**Comment by pooza** [comment]
実はこれ #2038 と同じケースです。
JSのアセット /mulukhiya/scripts/* を最小化する際にキャッシュが読み込めていない様です。
関連するクラスはこのあたり。
https://github.com/pooza/mulukhiya-toot-proxy/blob/master/app/lib/mulukhiya/storage/script_storage.rb

手元でなかなか再現しない為に対応が始められなかったのですが、ほぼ再起動で直る様です。
JSの最小化をどうしてもしなければいけないわけでもないので、デフォルトオフにしようという考えもあります。

**Comment by pooza** [comment]
キャッシュではなく execjs に前提ライブラリがあって、リリースノートに書き忘れたのだったのかも。
そうであれば別個の理由ですね。

トラブルのわりにはメリットが少ないので、最小化はやめましょう。

**Comment by karasugawasu** [comment]
確認ありがとうございます。
再起動やモロヘイヤの再配置（削除→Clone）など色々実は試していましたがダメでした。

` execjs に前提ライブラリ`　私の場合おそらくこれが該当かと思っています。
該当のリリースノート(4.2.2?)は特に前提ライブラリの件書いていないですね。

最小化メリット少ないのですね・・

**Comment by pooza** [comment]
```
webui:
  javascript:
    minimize: false
```
最小化オフをデフォルトとし、実験的機能とします。
trueにするならNode.jsのインストールを推奨ということで。

**Comment by pooza** [comment]
「推奨」というのは、利用できるJSランタイムがNode.js以外にもある様なので。
https://github.com/rails/execjs
