### ISSUE TITLE
投稿の添付画像が以前別の投稿に添付した画像に差し替えられてしまう

### ISSUE THREAD

**Issue by rnanba** [pooza/mulukhiya-toot-proxy#3164]
## 概要

投稿(キュア)に添付した画像が、投稿結果では別の画像に差し替えられている。差し替え後の画像は以前別の投稿に添付した画像である。

## 現象

以下の投稿に添付した画像の3枚目が添付した画像と異なる画像に差し替えられていました。
https://precure.ml/web/@rna/108744696064097830

この投稿は iPhone (iOS15.5)のTootle(10.0)によって、カメラロールの写真を添付して投稿されました。

問題の写真はiPhoneの標準カメラアプリで撮影されHEICで保存されていましたが、写真アプリ内で編集したため、JPEGで保存されているはずで、Tootleからの投稿時にはそのJPEGがそのままアップロードされているものと思われます。添付の zip ファイル内の IMG_7261.jpeg がその画像のはずです。ただし macOS の写真アプリで取り込んだものなので、バイナリ的に全く同じかどうかは不明です。

差し替えら後の画像は以前以下の投稿の4枚目に添付した画像です。
https://precure.ml/web/@rna/108739327091452113

この投稿は Firefox (103.0, Linux)によってキュアスタ！の WebUI からローカルファイルのPNG画像を添付して投稿されました。

添付の zip ファイル内の vlcsnap-20220724-083000-デリシャスパーティ◆プリキュア　第２０話あまねのマナーレッスン！憧れレストラン[デ][字].ts-00_25_10-00078.png がその画像です。

## 期待される動作

投稿に添付した画像がそのまま、もしくはその画像ファイルに由来する変換済みの画像で表示される。もしくは何らかのエラーが発生していたのであれば、投稿に失敗する。

## 再現手順

1. 添付の zip ファイル内の vlcsnap-20220724-083000-デリシャスパーティ◆プリキュア　第２０話あまねのマナーレッスン！憧れレストラン[デ][字].ts-00_25_10-00078.png を添付したキュアを WebUI から投稿する。
2. 添付の zip ファイル内の IMG_7261.jpeg を iPhone のカメラロールに保存して、それを添付したキュアを Tootle から投稿する。

ただし、以下の投稿で再現を試みた際には再現しませんでした(期待した画像が表示される)。
https://precure.ml/web/@rna/108764013322474856

## 環境

iPhone: iPhone 12 mini, iOS 15.5, Tootle 10.0
PC: Ryzen 3 pro 4350g with radeon graphics × 8 , Ubuntu 20.04.4 LTS, Firefox 103.0

[upload_files.zip](https://github.com/pooza/mulukhiya-toot-proxy/files/9259251/upload_files.zip)

**Comment by pooza** [comment]
#3159 #3160 が、この件と関連した対応。
解決の検証が必要。

**Comment by pooza** [comment]
現行バージョンとこの現象が発生した4.21.2のそれぞれで、いくつかのパターンで画像をアップしてみたが、再現できなかった。
4.21.3以降の対応で既に解決しているとは思うけど、現象の再現が出来ていない為、このissueはもう少し様子見。

**Comment by pooza** [comment]
その後問題が起きていないようなので、この問題は解決とする。
