### ISSUE TITLE
Annictのtheme_works_onlyがなくてもある時と同じ挙動になる

### ISSUE THREAD

**Issue by karasugawasu** [pooza/mulukhiya-toot-proxy#3419]
## 概要

Annictの設定でtheme_works_onlyをtrueにしていなくても、しているときと同様の挙動となっている

## 期待される動作

theme_works_only未指定時に指定されたテーマ以外の番組も投稿できる

## 再現手順

1. https://precure.ml/mulukhiya/app/config のAnnict設定に行く
2. 「タイトルに「プリキュア」が含まれる作品のみをレビュー対象とする」のチェックを入れない（外す）
3. プリキュア以外の番組で視聴記録をつける
4. キュアスタ！に投稿されない
 
## 環境
- キュアスタ！

**Comment by pooza** [comment]
「再現手順」は正常動作にみえますが、報告の内容に間違いありませんか？

**Comment by pooza** [comment]
チェックを外した時に、実際には外れていない。（画面上では外れているようにみえるが、Redisでは外れていない）可能性もありうると思いました。
よって、一度でもチェックを入れて保存したことがあるかどうかが重要になります。

**Comment by pooza** [comment]
該当機能が未実装だったようです。すみません。
次のバージョンで対応します。

**Comment by karasugawasu** [comment]
再現手順2は入れない（または外す）でしたね。
失礼しました。
