### ISSUE TITLE
モロヘイヤHOMEからremote_tagを無効→有効をすると再起動時に落ちたままになる

### ISSUE THREAD

**Issue by karasugawasu** [pooza/mulukhiya-toot-proxy#3432]
## 概要

モロヘイヤHOMEからremote_tagを無効→有効をすると再起動時に落ちたままになる

## 現象

モロヘイヤHOMEからremote_tagを無効にして再起動、
もう一度有効にして再起動をすると落ちたまま戻ってこなくなる。
ログには特にエラーは出ていなそう。

手動で再起動をかけると
```
---
controller: misskey
environment: production
config:
- The property '#/handler/remote_tag' did not contain a required property of 'services'
```
と言われるので、有効時に追加されたであろう以下を手動で削除すると起動するようになる
```
  remote_tag:
    disable: false
```

## 期待される動作

有効後に再起動を押してもちゃんと復帰する

## 再現手順

1. モロヘイヤHOMEのハンドラにアクセス
2. remote_tagを無効にして再起動を押す
3. 再度モロヘイヤHOMEのハンドラにアクセス
4. remote_tagを有効にして再起動を押す
5. モロヘイヤHOMEに復帰できない

## 環境

Misskey v13.11.2
mulukhiya-toot-proxy 4.27.5
Oracle Linux 8 (AArch64)

**Comment by pooza** [comment]
`/handler/remote_tag/services` が必要という、設定スキーマでの定義に違反している旨のエラーです。

disable化する際にはservices設定は不要なので、設定スキーマ側の誤りである可能性があります。
以前にWikiに書いた通りRemoteTagHandlerは（モロヘイヤそのものの意義として）disableにしてほしくない為、その意識からdisableにできない仕様をスキーマでは意識しているかもしれません。
